### ISSUE TITLE
bug: current deploy.yml cannot successfully create config file?

### ISSUE THREAD

**Issue by hukening81** [ThePiSquad/uiharu#14]
It seems like the docker build process uses a stand alone repository clone to the chekout action.
Our secret-to-file action created the config file inside the content root of checkout actons.

evidence:
![image](https://github.com/ThePiSquad/uiharu/assets/81057147/1ce35ae3-7cf7-4267-8c0a-21582b3f4757)

We didn't realize this bug because the target server uses the old image of version 0.1.0 not the buld from action.

**Comment by Tokyo469** [comment]
according to dockers document:

![Image](https://github.com/ThePiSquad/uiharu/assets/81057147/19be6be5-5426-4fcf-b4dd-ae1faf7f6ac2)
